# Step 1: Install dependencies and build the app
FROM node:18-alpine AS stage1
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Step 2: Run the app
FROM node:18-alpine
WORKDIR /app

COPY --from=stage1 /app ./

# Optional: if you use .env.production
# COPY .env.production ./

EXPOSE 3000
CMD ["npm", "start"]